-- Create hibernate_sequence so repositories can create
-- records.
CREATE SEQUENCE hibernate_sequence START 1;

-- Create condenser table
CREATE TABLE IF NOT EXISTS condenser
(
    id                INT          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    condenserId       VARCHAR(100) NOT NULL,
    name              VARCHAR(100) NOT NULL,
    image             VARCHAR(100) NOT NULL,
    dateAdded         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);